import { createInsertSchema } from "drizzle-zod";
import { users } from './auth';
import { categories, products, productImages } from './products';
import { addresses, cartItems, orders, orderItems } from './orders';
import { articles, news, pages } from './content';
import { reviews, wishlist, coupons } from './commerce';
import { brands, productAttributes, shippingMethods } from './catalog';
import { sliders, banners, landingPageSections } from './admin';
import { creditPoints, userWallets, userRequests } from './wallet';
import { searchAnalytics } from './analytics';
import { questions, answers } from './community';
import { settings } from './settings';

export const insertUserSchema = createInsertSchema(users);
export const insertCategorySchema = createInsertSchema(categories);
export const insertProductSchema = createInsertSchema(products);
export const insertProductImageSchema = createInsertSchema(productImages);
export const insertReviewSchema = createInsertSchema(reviews);
export const insertAddressSchema = createInsertSchema(addresses);
export const insertCartItemSchema = createInsertSchema(cartItems);
export const insertCouponSchema = createInsertSchema(coupons);
export const insertOrderSchema = createInsertSchema(orders);
export const insertOrderItemSchema = createInsertSchema(orderItems);
export const insertArticleSchema = createInsertSchema(articles);
export const insertNewsSchema = createInsertSchema(news);
export const insertPageSchema = createInsertSchema(pages);
export const insertBrandSchema = createInsertSchema(brands);
export const insertProductAttributeSchema = createInsertSchema(productAttributes);
export const insertShippingMethodSchema = createInsertSchema(shippingMethods);
export const insertCreditPointSchema = createInsertSchema(creditPoints);
export const insertUserWalletSchema = createInsertSchema(userWallets);
export const insertUserRequestSchema = createInsertSchema(userRequests);
export const insertSettingSchema = createInsertSchema(settings);
export const insertQuestionSchema = createInsertSchema(questions);
export const insertAnswerSchema = createInsertSchema(answers);
export const insertSliderSchema = createInsertSchema(sliders);
export const insertBannerSchema = createInsertSchema(banners);
export const insertLandingPageSectionSchema = createInsertSchema(landingPageSections);
export const insertSearchAnalyticsSchema = createInsertSchema(searchAnalytics);
